development:
  sessions:
    default:
      database: seshly_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: seshly_test
      hosts:
        - localhost:27017
        
# set these environment variables on your prod server
# <% if ENV['MONGOHQ_URL'] %>
#   <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
# production:
#   <<: *defaults
#   sessions:
#     default:
#       <<: *default_session
#       hosts:
#         - <%= uri.host %>:<%= uri.port %>
# <% end %>
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

